
# platform :ios, '9.0'

target 'Vision45' do
  
  use_frameworks!

  pod 'IQKeyboardManager'
  pod 'EZProgressHUD'
  pod 'SwiftyTabBarTransition'
  pod 'RealmSwift', '3.19.0'
  pod 'Toast-Swift', '~> 5.0.1'

end
